name: Node Countinuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci && npm install

      - name: Run build
        run: npm run build

  test:
      - name: Run tests
        run: npm run git-test

      # - name: Run linter
      #   run: npm run lint

      # - name: Run type checker
      #   run: npm run type-check

      # - name: Run coverage
      #   run: npm run coverage

      # - name: Run integration tests
      #   run: npm run integration-test

      # - name: Run security checks
      #   run: npm run security-check

      # - name: Run vulnerability checks
      #   run: npm run vulnerability-check

      # - name: Run audit
      #   run: npm audit

      # - name: Run dependency checks
      #   run: npm run dependency